// frontend/src/app/payment/success/page.tsx
'use client';

import React, { useEffect } from 'react';
import Link from 'next/link';
import { useCart } from '@/context/CartContext';

export default function PaymentSuccessPage() {
  const { fetchCart } = useCart();

  // On successful payment, the backend should clear the cart.
  // We refetch the cart here to update the UI state.
  useEffect(() => {
    fetchCart();
  }, [fetchCart]);

  return (
    <div className="container text-center py-5">
      <div className="display-1 text-success mb-3">✅</div>
      <h1 className="display-4 fw-bold">Payment Successful!</h1>
      <p className="lead text-muted my-4">
        Thank you for your purchase. Your order is being processed and you will receive a confirmation email shortly.
      </p>
      <div className="d-flex justify-content-center gap-3">
        <Link href="/" className="btn btn-primary btn-lg">
          Go to Homepage
        </Link>
        <Link href="/products" className="btn btn-outline-secondary btn-lg">
          Continue Shopping
        </Link>
      </div>
    </div>
  );
}

// frontend/src/routes/checkout/success/+page.svelte
<!-- frontend/src/routes/checkout/success/+page.svelte -->
<script>
    import { page } from '$app/stores';
    import { onMount } from 'svelte';
    import { cartItems, cartCount } from '$lib/stores/cartStore.js';

    const sessionId = $page.url.searchParams.get('session_id');

    // When this page loads, the order is complete.
    // We should clear the cart in our frontend store for a clean state.
    onMount(() => {
        $cartItems = [];
        $cartCount = 0;
    });

</script>
<div class="container py-5 text-center">
    <div class="card mx-auto" style="max-width: 500px;">
        <div class="card-body p-5">
            <h1 class="text-success">✓</h1>
            <h2>Payment Successful!</h2>
            <p class="lead">Thank you for your order.</p>
            <p>Your parts are on the way. You can view your order details in your profile.</p>
            {#if sessionId}
                <p class="small text-muted">Stripe Session ID: {sessionId}</p>
            {/if}
            <hr>
            <a href="/orders" class="btn btn-primary">View My Orders</a>
            <a href="/" class="btn btn-outline-secondary ms-2">Continue Shopping</a>
        </div>
    </div>
</div>
