// frontend/src/routes/auth/register/+page.svelte
<!-- frontend/src/routes/auth/register/+page.svelte -->
<script>
    import { goto } from '$app/navigation';
    import api from '$lib/api.js';
    import Swal from 'sweetalert2';

    let userData = {
        first_name: '',
        last_name: '',
        email: '',
        password: ''
    };
    let isLoading = false;

    async function handleRegister() {
        isLoading = true;
        try {
            const response = await api.post('/api/auth/register', userData);

            if (response.data.success) {
                Swal.fire({
                    title: 'Registration Successful!',
                    text: 'You have been registered and logged in.',
                    icon: 'success',
                    timer: 2000,
                    showConfirmButton: false
                });
                await goto('/');
            }
        } catch (error) {
            const errorMessage = error.response?.data?.message || 'Registration failed. Please try again.';
            Swal.fire({
                title: 'Registration Error',
                text: errorMessage,
                icon: 'error'
            });
        } finally {
            isLoading = false;
        }
    }
</script>

<div class="container py-5">
    <div class="row justify-content-center">
        <div class="col-md-6 col-lg-5">
            <div class="card shadow">
                <div class="card-body p-4 p-md-5">
                    <h2 class="text-center mb-4">Register</h2>
                    <form on:submit|preventDefault={handleRegister}>
                         <div class="row">
                            <div class="col-md-6 mb-3">
                                <label for="firstName" class="form-label">First Name</label>
                                <input type="text" class="form-control" id="firstName" bind:value={userData.first_name} required>
                            </div>
                            <div class="col-md-6 mb-3">
                                <label for="lastName" class="form-label">Last Name</label>
                                <input type="text" class="form-control" id="lastName" bind:value={userData.last_name} required>
                            </div>
                        </div>
                        <div class="mb-3">
                            <label for="email" class="form-label">Email address</label>
                            <input type="email" class="form-control" id="email" bind:value={userData.email} required>
                        </div>
                        <div class="mb-3">
                            <label for="password" class="form-label">Password</label>
                            <input type="password" class="form-control" id="password" bind:value={userData.password} required minlength="6">
                        </div>
                        <button type="submit" class="btn btn-primary w-100" disabled={isLoading}>
                            {#if isLoading}
                                <span class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span>
                                Registering...
                            {:else}
                                Register
                            {/if}
                        </button>
                    </form>
                    <div class="text-center mt-3">
                        <p>Already have an account? <a href="/auth/login">Login here</a></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

// frontend/src/app/auth/register/page.tsx
'use client';

import React, { useEffect } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { useFormStatus } from 'react-dom';

import { useAuth } from '@/context/AuthContext';
import { showAlert } from '@/lib/api';

// NEW: Define a state shape for our form action
interface ActionState {
  message: string;
  status: 'success' | 'error' | 'idle';
}

// NEW: A dedicated component for the submit button
function SubmitButton() {
  const { pending } = useFormStatus();
  return (
    <button type="submit" className="btn btn-primary w-100" disabled={pending}>
      {pending ? (
        <>
          <span className="spinner-border spinner-border-sm me-2" role="status" aria-hidden="true"></span>
          Creating Account...
        </>
      ) : (
        'Create Account'
      )}
    </button>
  );
}

export default function RegisterPage() {
  const { register } = useAuth();
  const router = useRouter();

// Define error shape for registration
interface RegistrationError {
  response?: {
    data?: {
      message?: string;
    };
  };
}

// NEW: The action function for registration
const handleRegisterAction = async (state: ActionState, formData: FormData): Promise<ActionState> => {
    const email = formData.get('email') as string;
    const password = formData.get('password') as string;
    const confirmPassword = formData.get('confirmPassword') as string;
    const first_name = formData.get('first_name') as string;
    const last_name = formData.get('last_name') as string;

    if (password !== confirmPassword) {
      return { status: 'error', message: 'Passwords do not match' };
    }
    if (password.length < 6) {
      return { status: 'error', message: 'Password must be at least 6 characters long' };
    }

    try {
      await register({ email, password, first_name, last_name });
      return { status: 'success', message: 'Account created successfully!' };
    } catch (error: unknown) {
      // Handle specific error structure
      const err = error as RegistrationError;
      return {
        status: 'error',
        message: err.response?.data?.message || 'Failed to create account. Please try again.',
      };
    }
  };

  const initialState: ActionState = { message: '', status: 'idle' };
  const [state, formAction] = React.useActionState(handleRegisterAction, initialState);

  // NEW: useEffect to handle side-effects from the action's result
  useEffect(() => {
    if (state.status === 'success') {
      showAlert.success(state.message);
      router.push('/');
    }
    if (state.status === 'error') {
      showAlert.error(state.message);
    }
  }, [state, router]);

  return (
    <div className="container py-5">
      <div className="row justify-content-center">
        <div className="col-md-8 col-lg-6">
          <div className="card shadow">
            <div className="card-body p-4">
              <div className="text-center mb-4">
                <h2 className="card-title">🏎️ Create Account</h2>
                <p className="text-muted">Join the RaceParts community</p>
              </div>

              {/* UPDATED: Form uses the `action` prop */}
              <form action={formAction}>
                <div className="row">
                  <div className="col-md-6 mb-3">
                    <label htmlFor="first_name" className="form-label">First Name</label>
                    <input type="text" className="form-control" id="first_name" name="first_name" required placeholder="Enter your first name"/>
                  </div>
                  <div className="col-md-6 mb-3">
                    <label htmlFor="last_name" className="form-label">Last Name</label>
                    <input type="text" className="form-control" id="last_name" name="last_name" required placeholder="Enter your last name"/>
                  </div>
                </div>
                <div className="mb-3">
                  <label htmlFor="email" className="form-label">Email Address</label>
                  <input type="email" className="form-control" id="email" name="email" required placeholder="Enter your email"/>
                </div>
                <div className="mb-3">
                  <label htmlFor="password" className="form-label">Password</label>
                  <input type="password" className="form-control" id="password" name="password" required placeholder="Enter your password" minLength={6}/>
                  <div className="form-text">Password must be at least 6 characters long.</div>
                </div>
                <div className="mb-3">
                  <label htmlFor="confirmPassword" className="form-label">Confirm Password</label>
                  <input type="password" className="form-control" id="confirmPassword" name="confirmPassword" required placeholder="Confirm your password"/>
                </div>
                <SubmitButton />
              </form>

              <div className="text-center mt-3">
                <p className="mb-0">
                  Already have an account?{' '}
                  <Link href="/auth/login" className="text-decoration-none">Sign in here</Link>
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
