// frontend/src/app/cart/page.tsx
'use client';

import React, { useState, useEffect } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import Image from 'next/image';
import { useCart } from '@/context/CartContext';
import { paymentAPI, showAlert } from '@/lib/api';
import { getStripe } from '@/lib/stripe';
import { useAuth } from '@/context/AuthContext';

export default function CartPage() {
  const { cart, loading, updateQuantity, removeFromCart } = useCart();
  const { user } = useAuth();
  const [checkoutLoading, setCheckoutLoading] = useState(false);
  const [isClient, setIsClient] = useState(false);
  const router = useRouter();

  useEffect(() => {
    setIsClient(true);
    if (!user) {
      router.push('/auth/login');
    }
  }, [user, router]);

  if (!isClient || !user || loading) {
    return (
      <div className="container d-flex justify-content-center align-items-center" style={{ minHeight: '60vh' }}>
        <div className="spinner-border text-primary" role="status">
          <span className="visually-hidden">Loading...</span>
        </div>
      </div>
    );
  }

  if (!cart || !Array.isArray(cart.items) || cart.items.length === 0) {
    return (
      <div className="container text-center py-5">
        <div className="display-1 text-muted mb-3">🛒</div>
        <h2 className="mb-3">Your cart is empty</h2>
        <p className="text-muted mb-4">Looks like you haven&apos;t added anything to your cart yet.</p>
        <Link href="/products" className="btn btn-primary btn-lg">
          Start Shopping
        </Link>
      </div>
    );
  }
  
  const handleQuantityChange = (itemId: number, newQuantity: number) => {
    if (newQuantity >= 1) {
      updateQuantity(itemId, newQuantity);
    }
  };

  const handleCheckout = async () => {
    setCheckoutLoading(true);
    try {
      console.log('Initiating checkout process...');
      
      // 1. Create checkout session
      const response = await paymentAPI.createCheckoutSession({
        origin: window.location.origin,
      });
      
      console.log('Checkout session response:', response);
      
      if (!response.data || !response.data.id) {
        throw new Error('Invalid response from server: Missing session id');
      }
      
      const { id: sessionId } = response.data;
      console.log('Retrieved session id:', sessionId);

      // 2. Load Stripe.js
      const stripe = await getStripe();
      if (!stripe) {
        throw new Error('Stripe.js failed to load. Please try again.');
      }
      
      console.log('Redirecting to Stripe Checkout with session id:', sessionId);
      
      // 3. Redirect to Stripe Checkout
      const { error } = await stripe.redirectToCheckout({
        sessionId: sessionId
      });
      
      if (error) {
        console.error('Stripe redirect error:', error);
        throw new Error(error.message || 'Failed to redirect to checkout.');
      }
    } catch (error) {
      console.error('Checkout error:', error);
      const errorMessage = error instanceof Error 
        ? error.message 
        : 'Could not initiate checkout. Please try again.';
      showAlert.error(errorMessage);
    } finally {
      setCheckoutLoading(false);
    }
  };

  const formatPrice = (price: number) => {
    return new Intl.NumberFormat('th-TH', { style: 'currency', currency: 'THB' }).format(price);
  };
  


  return (
    <div className="container py-5">
      <h1 className="display-5 fw-bold mb-4">Your Shopping Cart</h1>
      <div className="row">
        <div className="col-lg-8">
          {cart.items.map((item) => (
            <div key={item.id} className="card mb-3 shadow-sm">
              <div className="card-body">
                <div className="row g-3 align-items-center">
                  <div className="col-md-2 col-4">
                    <div className="position-relative" style={{ width: '100%', aspectRatio: '1/1' }}>
                      <Image
                        src={item?.Product?.images?.[0] || '/placeholder.svg'}
                        alt={item?.Product?.name || 'Product image'}
                        fill
                        className="img-fluid rounded"
                        style={{ objectFit: 'cover' }}
                        sizes="(max-width: 768px) 100vw, 150px"
                      />
                    </div>
                  </div>
                  <div className="col-md-4 col-8">
                    <h5 className="mb-1">{item?.Product?.name || 'Unnamed Product'}</h5>
                    <p className="text-muted small mb-0">Price: {item?.Product?.price ? formatPrice(item.Product.price) : 'N/A'}</p>
                  </div>
                  <div className="col-md-3 col-6">
                    <div className="input-group input-group-sm">
                      <span className="input-group-text">Qty</span>
                      <input
                        type="number"
                        className="form-control"
                        value={item.quantity}
                        min="1"
                        onChange={(e) => handleQuantityChange(item.id, parseInt(e.target.value))}
                      />
                    </div>
                  </div>
                  <div className="col-md-2 col-4 text-end">
                    <p className="fw-bold mb-0">{item?.Product?.price ? formatPrice(item.Product.price * item.quantity) : 'N/A'}</p>
                  </div>
                  <div className="col-md-1 col-2 text-end">
                    <button 
                      className="btn btn-sm btn-outline-danger" 
                      onClick={() => removeFromCart(item.id)}
                      title="Remove item"
                    >
                      ×
                    </button>
                  </div>
                </div>
              </div>
            </div>
          ))}
        </div>

        <div className="col-lg-4">
          <div className="card shadow-sm">
            <div className="card-body">
              <h4 className="card-title">Order Summary</h4>
              <ul className="list-group list-group-flush">
                <li className="list-group-item d-flex justify-content-between align-items-center">
                  Subtotal
                  <span>{formatPrice(cart.subtotal)}</span>
                </li>
                <li className="list-group-item d-flex justify-content-between align-items-center">
                  Shipping
                  <span className="text-success">Free</span>
                </li>
                <li className="list-group-item d-flex justify-content-between align-items-center fw-bold h5">
                  Total
                  <span>{formatPrice(cart.subtotal)}</span>
                </li>
              </ul>
              <button 
                className="btn btn-primary w-100 mt-3 btn-lg" 
                onClick={handleCheckout} 
                disabled={checkoutLoading}
              >
                {checkoutLoading ? (
                  <>
                    <span className="spinner-border spinner-border-sm me-2" role="status" aria-hidden="true"></span>
                    Processing...
                  </>
                ) : (
                  'Proceed to Checkout'
                )}
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

// frontend/src/routes/cart/+page.svelte
<!-- frontend/src/routes/cart/+page.svelte -->
<script>
    import { cartItems, cartCount } from '$lib/stores/cartStore.js';
    import api from '$lib/api.js';
    import Swal from 'sweetalert2';
    import { onMount } from 'svelte';

    let subtotal = 0;
    let isLoading = false;

    // Reactive statement to calculate subtotal whenever the cart items change
    $: {
        if ($cartItems && $cartItems.length > 0) {
            subtotal = $cartItems.reduce((sum, item) => sum + item.quantity * item.Product.price, 0);
        } else {
            subtotal = 0;
        }
    }

    async function updateQuantity(itemId, newQuantity) {
        if (newQuantity < 1) {
            return removeItem(itemId);
        }
        try {
            await api.patch(`/api/cart/${itemId}`, { quantity: newQuantity });
            // Update the store for instant UI feedback
            $cartItems = $cartItems.map(item => 
                item.id === itemId ? { ...item, quantity: newQuantity } : item
            );
            $cartCount = $cartItems.reduce((sum, item) => sum + item.quantity, 0);
        } catch (error) {
            Swal.fire('Error', 'Could not update item quantity.', 'error');
        }
    }

    async function removeItem(itemId) {
        try {
            await api.delete(`/api/cart/${itemId}`);
            const removedItem = $cartItems.find(item => item.id === itemId);
            // Update the store for instant UI feedback
            $cartItems = $cartItems.filter(item => item.id !== itemId);
            $cartCount -= removedItem.quantity;
        } catch (error) {
            Swal.fire('Error', 'Could not remove item from cart.', 'error');
        }
    }

    async function handleCheckout() {
        isLoading = true;
        Swal.fire({
            title: 'Redirecting to Checkout',
            text: 'Please wait while we prepare your secure payment page.',
            allowOutsideClick: false,
            didOpen: () => {
                Swal.showLoading();
            }
        });

        try {
            const response = await api.post('/api/payment/create-checkout-session', {
                // Pass the browser's origin so Stripe can redirect back correctly
                origin: window.location.origin 
            });

            if (response.data.url) {
                // Redirect the user to the Stripe Checkout page
                window.location.href = response.data.url;
            }
        } catch (error) {
            Swal.fire('Checkout Error', 'Could not initiate the checkout process. Please try again.', 'error');
        } finally {
            // This might not be reached if redirect is successful
            isLoading = false; 
        }
    }
</script>

<div class="container py-5">
    <h1 class="mb-4">Your Shopping Cart</h1>

    {#if $cartItems && $cartItems.length > 0}
        <div class="row">
            <!-- Cart Items -->
            <div class="col-lg-8">
                {#each $cartItems as item (item.id)}
                    <div class="card mb-3">
                        <div class="card-body">
                            <div class="d-flex justify-content-between">
                                <div class="d-flex flex-row align-items-center">
                                    <div>
                                        <img src="https://dummyimage.com/100x100/dee2e6/6c757d.jpg" class="img-fluid rounded-3" alt={item.Product.name} style="width: 65px;">
                                    </div>
                                    <div class="ms-3">
                                        <h5>{item.Product.name}</h5>
                                        <p class="small mb-0">Product Slug: {item.Product.slug}</p>
                                    </div>
                                </div>
                                <div class="d-flex flex-row align-items-center">
                                    <div style="width: 100px;">
                                        <input type="number" min="1" class="form-control form-control-sm text-center" value={item.quantity} on:change={(e) => updateQuantity(item.id, parseInt(e.target.value))} />
                                    </div>
                                    <div style="width: 100px;" class="ms-4">
                                        <h5 class="mb-0">${(item.Product.price * item.quantity).toFixed(2)}</h5>
                                    </div>
                                    <button on:click={() => removeItem(item.id)} class="btn btn-link text-danger ms-2"><i class="fas fa-trash fa-lg"></i>X</button>
                                </div>
                            </div>
                        </div>
                    </div>
                {/each}
            </div>

            <!-- Cart Summary -->
            <div class="col-lg-4">
                <div class="card bg-primary text-white rounded-3">
                    <div class="card-body">
                        <h5 class="card-title">Cart Summary</h5>
                        <hr>
                        <div class="d-flex justify-content-between mb-4">
                            <p class="mb-2">Subtotal</p>
                            <p class="mb-2">${subtotal.toFixed(2)}</p>
                        </div>

                        <button type="button" class="btn btn-info btn-block btn-lg w-100" on:click={handleCheckout} disabled={isLoading}>
                            <div class="d-flex justify-content-between">
                                <span>Checkout</span>
                                <span>${subtotal.toFixed(2)} <i class="fas fa-long-arrow-alt-right ms-2"></i></span>
                            </div>
                        </button>
                    </div>
                </div>
            </div>
        </div>
    {:else}
        <div class="text-center py-5">
            <h2>Your cart is empty.</h2>
            <p>Looks like you haven't added any parts yet!</p>
            <a href="/" class="btn btn-primary mt-3">Start Shopping</a>
        </div>
    {/if}
</div>
